#!/bin/sh

case $1 in
    start)
        echo "Starting aesdsocket server ..."
        start-stop-daemon -S -n -x aesdsocket -a /usr/bin/aesdsocket -- -d
        ;;
    stop)
        echo "Stopping aesksocket server ..."
        start-stop-daemon -K -n aesdsocket
        ;;
    *)
        echo "Usage is $0 [start/stop]"
    exit 1
esac


exit 0
